### ISSUE TITLE
After upgrading to 1.2.500 (apscheduler was updated too): AttributeError: 'IntervalTrigger' object has no attribute '__dict__'

### ISSUE THREAD

**Issue by antivirtel** [Flexget/Flexget#1005]
```
2016-04-03 13:27 WARNING  check                         Config line 4 is likely missing ':' at the end
2016-04-03 13:27 WARNING  check                         Config line 10 is likely missing ':' at the end
2016-04-03 13:27 VERBOSE  check                         Pre-checked 411 configuration lines
2016-04-03 13:27 VERBOSE  check                         Checking config file `/home/osmc/.flexget/config.yml`
2016-04-03 13:27 VERBOSE  check                         Config passed check.
2016-04-03 13:28 ERROR    apscheduler.jobstores                 Unable to restore job "527a1814bb7c58106711f1f3fa208c5efb3b5af2" -- removing it
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/jobstores/sqlalchemy.py", line 135, in _get_jobs
    jobs.append(self._reconstitute_job(row.job_state))
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/jobstores/sqlalchemy.py", line 119, in _reconstitute_job
    job_state = pickle.loads(job_state)
AttributeError: 'IntervalTrigger' object has no attribute '__dict__'
2016-04-03 13:28 ERROR    apscheduler.jobstores                 Unable to restore job "3805830e723214ea9ef8468e43184f0a70ca5b57" -- removing it
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/jobstores/sqlalchemy.py", line 135, in _get_jobs
    jobs.append(self._reconstitute_job(row.job_state))
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/jobstores/sqlalchemy.py", line 119, in _reconstitute_job
    job_state = pickle.loads(job_state)
AttributeError: 'IntervalTrigger' object has no attribute '__dict__'
2016-04-03 13:28 INFO     scheduler                     Starting scheduler
2016-04-03 13:28 INFO     webui                         Not starting webui as it's disabled or not set in the config
2016-04-03 13:28 INFO     web_server                    Web interface available at http://127.0.0.1:8080
```

Are the tests were passed, and didn't show this error?

**Comment by cvium** [comment]
Why would the tests show this error? This has to do with apscheduler changing the way it saves the jobs. It's not related to Flexget nor did it seem to have an impact.

This is on the devs of apscheduler.

**Comment by antivirtel** [comment]
Fixed in [next apscheduler release (v3.1.1)](https://github.com/agronholm/apscheduler/blob/master/docs/versionhistory.rst#311).
