### ISSUE TITLE
Discover plugin crashes with 'NoneType' object has no attribute 'read'

### ISSUE THREAD

**Issue by xathin** [Flexget/Flexget#696]
Every time my task looks for shows, it is coming up with the following BUG. This started since I updated to 1.2.403.

2015-12-10 19:24 CRITICAL task          My-TV-Shows-Find-Next-Following BUG: Unhandled error in plugin discover: 'NoneType' object has no attribute 'read'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/discover.py", line 268, in on_task_input
    entries = self.estimated(entries)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/discover.py", line 190, in estimated
    est_date = estimator.estimate(entry)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/estimators/est_released.py", line 28, in estimate
    estimate = estimator(entry)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/estimators/est_release_series_tvmaze.py", line 52, in estimate
    episode = lookup(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tvmaze.py", line 406, in episode_lookup
    episode = TVMazeEpisodes(pytvmaze_episode, series.tvmaze_id)
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/state.py", line 306, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/state.py", line 303, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tvmaze.py", line 159, in __init__
    self.update(episode)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tvmaze.py", line 176, in update
    self.airstamp = parser.parse(episode.airstamp)
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 1008, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 392, in parse
    res = self._parse(timestr, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 492, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 174, in split
    return list(cls(s))
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 171, in next
    return self.__next__()  # Python 2.x support
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 164, in __next__
    token = self.get_token()
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 82, in get_token
    nextchar = self.instream.read(1)
AttributeError: 'NoneType' object has no attribute 'read'

**Comment by crawln45** [comment]
What version of Flexget are you running. Believe this issue has been fixed already in the latest version.

**Comment by xathin** [comment]
flexget -V
1.2.403
You are on the latest release.

**Comment by xathin** [comment]
As I said, this bug was only present and noticed after upgrading to the latest version. Crash reports are being generated every time the task is being run, whereas I had no crash reports prior to updating to 1.2.403.

**Comment by crawln45** [comment]
Intresting sorry about that. Seen the same error from previous errors when there wasn't an airdate yet because it hadn't aired. I'll look into it real quick.

**Comment by crawln45** [comment]
Seems like the package pytvmaze needs to be updated. Please update this package using pip and let me know if it still does it.
```
pip install --upgrade pytvmaze
```

**Comment by gazpachoking** [comment]
Looks like our release job stalled for a few days. This was indeed fixed, but no release had it. 1.2.404 is out now and should fix.
