### ISSUE TITLE
Imdb lazy_lookup error on 3.15.40 and 3.18.7

### ISSUE THREAD

**Issue by terrellgf** [Flexget/Flexget#4637]
### Summary

My configuration works fine on version 3.15.31
When I run my configuration with versions 3.15.40 and 3.18.7 it works successfully for a few times. Then it crashes with errors and floods tens of thousands of logs every day.
I had to rollback to 3.15.31 and it works fine now.
Please help me.

2025-09-16 21:46:39 ERROR lazy_lookup XXXXX-Movies Unhandled error in lazy lookup plugin: 'NoneType' object has no attribute 'string'
2025-09-16 21:46:39 CRITICAL manager XXXXX-Movies An unexpected crash has occurred. Writing crash report to /config/crash_report.2025.09.16.214639067498.log. Please verify you are running the latest version of flexget by using "flexg
et -V" from CLI or by using version_checker plugin at https://flexget.com/Plugins/version_checker. You are currently using version 3.18.7
2025-09-16 21:46:46 CRITICAL task XXXXX-Movies BUG: Unhandled error in plugin if: 'NoneType' object has no attribute 'string'
Traceback (most recent call last):

File "/usr/lib/python3.12/threading.py", line 1032, in _bootstrap
self._bootstrap_inner()
│ └ <function Thread._bootstrap_inner at 0x7fcac6752520>
└ <Thread(task_queue, started daemon 140508674849592)>
File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
self.run()
│ └ <function Thread.run at 0x7fcac6752200>
└ <Thread(task_queue, started daemon 140508674849592)>
File "/usr/lib/python3.12/threading.py", line 1012, in run
self._target(*self._args, **self._kwargs)
│ │ │ │ │ └ {}
│ │ │ │ └ <Thread(task_queue, started daemon 140508674849592)>
│ │ │ └ ()
│ │ └ <Thread(task_queue, started daemon 140508674849592)>
│ └ <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x7fcabba5bd40>>
└ <Thread(task_queue, started daemon 140508674849592)>
File "/usr/lib/python3.12/site-packages/flexget/task_queue.py", line 51, in run
self.current_task.execute()
│ │ └ <function Task.execute at 0x7fcac2537380>
│ └ <flexget.task.Task object at 0x7fcab802be60>
└ <flexget.task_queue.TaskQueue object at 0x7fcabba5bd40>
File "/usr/lib/python3.12/site-packages/flexget/task.py", line 93, in wrapper
return func(self, *args, **kw)
│ │ │ └ {}
│ │ └ ()
│ └ <flexget.task.Task object at 0x7fcab802be60>
└ <function Task.execute at 0x7fcac25372e0>
File "/usr/lib/python3.12/site-packages/flexget/task.py", line 705, in execute
self._execute()
│ └ <function Task._execute at 0x7fcac2537240>
└ <flexget.task.Task object at 0x7fcab802be60>
File "/usr/lib/python3.12/site-packages/flexget/task.py", line 676, in _execute
self.__run_task_phase(phase)
│ └ 'filter'
└ <flexget.task.Task object at 0x7fcab802be60>
File "/usr/lib/python3.12/site-packages/flexget/task.py", line 508, in __run_task_phase
response = self.__run_plugin(plugin, phase, args)
│ │ │ └ (<flexget.task.Task object at 0x7fcab802be60>, [{"'documentary' in (imdb_genres or [])": 'reject'}, {"'musical' in (imdb_genr...
│ │ └ 'filter'
│ └ <PluginInfo(name=if)>
└ <flexget.task.Task object at 0x7fcab802be60>

File "/usr/lib/python3.12/site-packages/flexget/task.py", line 541, in __run_plugin
result = method(*args, **kwargs)
│ │ └ {}
│ └ (<flexget.task.Task object at 0x7fcab802be60>, [{"'documentary' in (imdb_genres or [])": 'reject'}, {"'musical' in (imdb_genr...
└ <Event(name=plugin.if.filter,func=handle_phase,priority=80)>
File "/usr/lib/python3.12/site-packages/flexget/event.py", line 24, in call
return self.func(*args, **kwargs)
│ │ │ └ {}
│ │ └ (<flexget.task.Task object at 0x7fcab802be60>, [{"'documentary' in (imdb_genres or [])": 'reject'}, {"'musical' in (imdb_genr...
│ └ <function FilterIf.getattr..handle_phase at 0x7fcabbbb23e0>
└ <Event(name=plugin.if.filter,func=handle_phase,priority=80)>
File "/usr/lib/python3.12/site-packages/flexget/plugins/filter/if_condition.py", line 87, in handle_phase
method(*methods[method])
│ │ └ <Event(name=plugin.imdb.filter,func=on_task_filter,priority=120)>
│ └ {<Event(name=plugin.imdb.filter,func=on_task_filter,priority=120)>: (<flexget.task.Task object at 0x7fcac046e060>, {'min_year...
└ <Event(name=plugin.imdb.filter,func=on_task_filter,priority=120)>
File "/usr/lib/python3.12/site-packages/flexget/event.py", line 24, in call
return self.func(*args, **kwargs)
│ │ │ └ {}
│ │ └ (<flexget.task.Task object at 0x7fcac046e060>, {'min_year': 2010, 'min_score': 6.8, 'min_votes': 10})
│ └ <bound method FilterImdb.on_task_filter of <flexget.components.imdb.imdb.FilterImdb object at 0x7fcabbc29160>>
└ <Event(name=plugin.imdb.filter,func=on_task_filter,priority=120)>
File "/usr/lib/python3.12/site-packages/flexget/components/imdb/imdb.py", line 114, in on_task_filter
lookup(entry)
│ └ <Entry(title=Hard Hit 2021 1080p IQiyi WEB-DL AAC H.265-HBO,state=undecided)>
└ <bound method internet.call..wrapped_func of <flexget.components.imdb.imdb_lookup.ImdbLookup object at 0x7fcabbc2...
File "/usr/lib/python3.12/site-packages/flexget/plugin.py", line 128, in wrapped_func
return func(*args, **kwargs)
│ │ └ {}
│ └ (<flexget.components.imdb.imdb_lookup.ImdbLookup object at 0x7fcabbc29220>, <Entry(title=Hard Hit 2021 1080p IQiyi WEB-DL AAC...
└ <function with_session..decorator..wrapper at 0x7fcabe1d5b20>
File "/usr/lib/python3.12/site-packages/flexget/utils/database.py", line 34, in wrapper
return func(*args, **kwargs)
│ │ └ {'session': <sqlalchemy.orm.session.ContextSession object at 0x7fcac229cd10>}
│ └ (<flexget.components.imdb.imdb_lookup.ImdbLookup object at 0x7fcabbc29220>, <Entry(title=Hard Hit 2021 1080p IQiyi WEB-DL AAC...
└ <function ImdbLookup.lookup at 0x7fcabe1d5940>
File "/usr/lib/python3.12/site-packages/flexget/components/imdb/imdb_lookup.py", line 218, in lookup
movie = self._parse_new_movie(entry['imdb_url'], session)
│ │ │ └ <sqlalchemy.orm.session.ContextSession object at 0x7fcac229cd10>
│ │ └ <Entry(title=Hard Hit 2021 1080p IQiyi WEB-DL AAC H.265-HBO,state=undecided)>
│ └ <function ImdbLookup._parse_new_movie at 0x7fcabe1d5bc0>
└ <flexget.components.imdb.imdb_lookup.ImdbLookup object at 0x7fcabbc29220>
File "/usr/lib/python3.12/site-packages/flexget/components/imdb/imdb_lookup.py", line 262, in _parse_new_movie
parser.parse(imdb_url)
│ │ └ 'https://www.imdb.com/title/tt14980972/'
│ └ <function ImdbParser.parse at 0x7fcac01e74c0>
└ <flexget.components.imdb.utils.ImdbParser object at 0x7fcab8b0ff50>
File "/usr/lib/python3.12/site-packages/flexget/components/imdb/utils.py", line 251, in parse
data = json.loads(soup.find('script', {'type': 'application/ld+json'}).string)
│ │ │ └ <function Tag.find at 0x7fcac2400c20>
│ │ └
│ └ <function loads at 0x7fcac5ad5b20>
└ <module 'json' from '/usr/lib/python3.12/json/init.py'>

AttributeError: 'NoneType' object has no attribute 'string'
2025-09-16 21:46:46 CRITICAL manager XXXXX-Movies An unexpected crash has occurred. Writing crash report to /config/crash_report.2025.09.16.214646687829.log. Please verify you are running the latest version of flexget by using "flexg
et -V" from CLI or by using version_checker plugin at https://flexget.com/Plugins/version_checker. You are currently using version 3.18.7
2025-09-16 21:46:46 WARNING task XXXXX-Movies Aborting task (plugin: if)

### Minimal reproducible config

```yaml

```

### Log

```text

```

### Additional information

**FlexGet Version:** 
**Python Version:** 
**OS Version:** 
**Installation Method:** 
**Using Daemon (yes/no):**

**Comment by vivodi** [comment]
Based on the error message you provided, I tried to reproduce it with the following code:

```python
from flexget.components.imdb.utils import ImdbParser

parser = ImdbParser()
parser.parse('https://www.imdb.com/title/tt14980972/')
```

However, I wasn’t able to trigger the error, and the relevant code is already thoroughly tested in [test_imdb_parser.py](https://github.com/Flexget/Flexget/blob/develop/tests/test_imdb_parser.py).

I’m inclined to think this might be due to your access to IMDb being restricted after too many requests.

**Comment by terrellgf** [comment]
> Based on the error message you provided, I tried to reproduce it with the following code:
> 
> from flexget.components.imdb.utils import ImdbParser
> 
> parser = ImdbParser()
> parser.parse('https://www.imdb.com/title/tt14980972/')
> However, I wasn’t able to trigger the error, and the relevant code is already thoroughly tested in [test_imdb_parser.py](https://github.com/Flexget/Flexget/blob/develop/tests/test_imdb_parser.py).
> 
> I’m inclined to think this might be due to your access to IMDb being restricted after too many requests.

If it was restricted by IMDb, shouldn't everything return to normal after rolling back to version 3.15.31？

**Comment by vivodi** [comment]
Could you share your configuration so others can try to reproduce the issue?

From the code, the part related to the error looks quite simple and I’m not seeing any issues on my side, so even if you share your configuration, I still might not be able to reproduce it.

**Comment by terrellgf** [comment]
> Could you share your configuration so others can try to reproduce the issue?
> 
> From the code, the part related to the error looks quite simple and I’m not seeing any issues on my side, so even if you share your configuration, I still might not be able to reproduce it.

My configuration is quite complicated. Let me first take a look at some of the imdb related configurations.

variables:
  movies_imdb_score_threshold:
    horror_ge_2010: 6
    other_ge_2010: 6.8
    other_ge_2000: 7
    other_ge_1990: 7.5
    other_le_1989: 8.5

templates:
  movie:
    seen_movies:
      matching: strict
    proper_movies: no
    upgrade:
      tracking: yes
    imdb_lookup: yes
    require_field:
      - imdb_year
      - imdb_url
      - imdb_genres
      - imdb_score
      - imdb_languages
      - imdb_votes
    if:
      - "'documentary' in (imdb_genres or [])": reject
      - "'musical' in (imdb_genres or [])": reject
      - "'biography' in (imdb_genres or [])": reject
      - "'music' in (imdb_genres or [])": reject
      - "'malayalam' in (imdb_languages or [])": reject
      - "'hindi' in (imdb_languages or [])": reject
      - "'urdu' in (imdb_languages or [])": reject
      - "'tamil' in (imdb_languages or [])": reject
      - "'kannada' in (imdb_languages or [])": reject
      - "'telugu' in (imdb_languages or [])": reject
      - "'punjabi' in (imdb_languages or [])": reject
      - "'marathi' in (imdb_languages or [])": reject
      - "'thai' in (imdb_languages or [])": reject
      - "'indonesian' in (imdb_languages or [])": reject
      - "'bengail' in (imdb_languages or [])": reject
      - "'horror' in (imdb_genres or [])":
          imdb:
            min_year: 2010
            min_score: '{? movies_imdb_score_threshold.horror_ge_2010 ?}'
            min_votes: 10
      - "'horror' not in (imdb_genres or [])":
            imdb:
              min_year: 2010
              min_score: '{? movies_imdb_score_threshold.other_ge_2010 ?}'
              min_votes: 10
      - "'horror' not in (imdb_genres or [])":
          imdb:
            min_year: 2000
            min_score: '{? movies_imdb_score_threshold.other_ge_2000 ?}'
            min_votes: 20
      - "'horror' not in (imdb_genres or [])":
          imdb:
            min_year: 1990
            min_score: '{? movies_imdb_score_threshold.other_ge_1990 ?}'
            min_votes: 30
      - "'horror' not in (imdb_genres or [])":
          imdb:
            max_year: 1999
            min_score: '{? movies_imdb_score_threshold.other_le_1989 ?}'
            min_votes: 40

**Comment by terrellgf** [comment]
After upgrading to 3.18.11, the problem no longer occurs. Is there a fix?

**Comment by vivodi** [comment]
> After upgrading to 3.18.11, the problem no longer occurs. Is there a fix?

We didn’t ship any actual fixes — 3.18.11 just has dependency updates compared to 3.18.7.

Like I said before, I think this is only a temporary issue and not version-related.

**Comment by ranirahn** [comment]
I have this error for 2 days now produced 4000 crash reports. flexget version is 3.18.39. Because it asked me to update i dont remember what was the version that started this, but because updating flexget did not fix the issue i come looking if anyone else have same problem. did not expect it to be half year old problem 😆 

Edit: Turned IMDB_lookup off and no crash reports anymore. But I noticed that imdb_watchlist also giving error. html status code 202. if i dont have my watchlist then the lookup is useless anyway. nothing will be downloaded. So I have 2 problems that are related to IMDB right now. And checked with curl what imdb responds
```
curl -I https://www.imdb.com
HTTP/2 202
server: CloudFront
date: Fri, 23 Jan 2026 08:27:06 GMT
content-length: 0
x-amzn-waf-action: challenge
cache-control: no-store, max-age=0
content-type: text/html; charset=UTF-8
access-control-allow-origin: *
access-control-max-age: 86400
access-control-allow-methods: OPTIONS,GET,POST
access-control-expose-headers: x-amzn-waf-action
x-cache: Error from cloudfront

``` 

So this challenge probably stops all action? Maybe I need to change user-agent or something?

Edit2: Temporary solution was to add cookie after user-agent and I copied that session-id in there that I had in my browser and both imdb_whatchlist and imdb_lookup started working. So its just IMDB bot protection that dont let plugins to work. I hope there will be some solution that flexget can do that automatically some how.

Edit3: I was wrong. imdb_lookup does not work still. imdb_watchlist gives me my list, but lookup makes crash_report for every item.

**Comment by jmaliska** [comment]
> I have this error for 2 days now produced 4000 crash reports. flexget version is 3.18.39. Because it asked me to update i dont remember what was the version that started this, but because updating flexget did not fix the issue i come looking if anyone else have same problem. did not expect it to be half year old problem 😆
> 
> Edit: Turned IMDB_lookup off and no crash reports anymore. But I noticed that imdb_watchlist also giving error. html status code 202. if i dont have my watchlist then the lookup is useless anyway. nothing will be downloaded. So I have 2 problems that are related to IMDB right now. And checked with curl what imdb responds
> 
> ```
> curl -I https://www.imdb.com
> HTTP/2 202
> server: CloudFront
> date: Fri, 23 Jan 2026 08:27:06 GMT
> content-length: 0
> x-amzn-waf-action: challenge
> cache-control: no-store, max-age=0
> content-type: text/html; charset=UTF-8
> access-control-allow-origin: *
> access-control-max-age: 86400
> access-control-allow-methods: OPTIONS,GET,POST
> access-control-expose-headers: x-amzn-waf-action
> x-cache: Error from cloudfront
> ```
> 
> So this challenge probably stops all action? Maybe I need to change user-agent or something?
> 
> Edit2: Temporary solution was to add cookie after user-agent and I copied that session-id in there that I had in my browser and both imdb_whatchlist and imdb_lookup started working. So its just IMDB bot protection that dont let plugins to work. I hope there will be some solution that flexget can do that automatically some how.
> 
> Edit3: I was wrong. imdb_lookup does not work still. imdb_watchlist gives me my list, but lookup makes crash_report for every item.

I have the same problem for about 2 days.

**Comment by ranirahn** [comment]
I have looked into it a little and its bot protection that blocks the connection. imdb_watchlist and imdb_lookup dont work. both run into this bot protection. going back to exporting csv and tmdb_lookup combo until there is solution for this.

**Comment by paranoidi** [comment]
Seems to be working for me right now. Added some safe checks in case bot protections are encountered so nobody disk filled with crash reports.

**Comment by antczakp** [comment]
It was working for me for a while and now stopped again. I seem to have no trouble accessing the imdb page, but when done through the parser it just returns an empty page 😕

**Comment by paranoidi** [comment]
Not relevant issue anymore. Parsing switched to use playwright.
