### ISSUE TITLE
BUG: Unhandled error in plugin from_transmission: 'Client' object has no attribute 'http_handler

### ISSUE THREAD

**Issue by ProteinPig** [Flexget/Flexget#2799]
I'm using wiserain/flexget docker version, after someday auto update, this bug appear.

2021-01-05 09:56:57 DEBUG    task          clean_finished_seeds executing clean_finished_seeds
2021-01-05 09:56:57 DEBUG    template      clean_finished_seeds Merging template global into task clean_finished_seeds
2021-01-05 09:56:57 DEBUG    disable       clean_finished_seeds Disabled plugins: seen, seen_info_hash
2021-01-05 09:56:57 DEBUG    remember_rej  clean_finished_seeds Task config has changed since last run, purging remembered entries.
2021-01-05 09:56:57 CRITICAL task          clean_finished_seeds BUG: Unhandled error in plugin from_transmission: 'Client' object has no attribute 'http_handler'
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f303c651ca0>
    └ <Thread(task_queue, started daemon 139845052197664)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f303c6519d0>
    └ <Thread(task_queue, started daemon 139845052197664)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(task_queue, started daemon 139845052197664)>
    │    │        │    └ ()
    │    │        └ <Thread(task_queue, started daemon 139845052197664)>
    │    └ <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x7f3037c8c730>>
    └ <Thread(task_queue, started daemon 139845052197664)>
  File "/usr/lib/python3.8/site-packages/flexget/task_queue.py", line 46, in run
    self.current_task.execute()
    │    │            └ <function Task.execute at 0x7f303ab04550>
    │    └ <flexget.task.Task object at 0x7f30364a29d0>
    └ <flexget.task_queue.TaskQueue object at 0x7f3037c8c730>
  File "/usr/lib/python3.8/site-packages/flexget/task.py", line 87, in wrapper
    return func(self, *args, **kw)
           │    │      │       └ {}
           │    │      └ ()
           │    └ <flexget.task.Task object at 0x7f30364a29d0>
           └ <function Task.execute at 0x7f303ab044c0>
  File "/usr/lib/python3.8/site-packages/flexget/task.py", line 722, in execute
    self._execute()
    │    └ <function Task._execute at 0x7f303ab04430>
    └ <flexget.task.Task object at 0x7f30364a29d0>
  File "/usr/lib/python3.8/site-packages/flexget/task.py", line 688, in _execute
    self.__run_task_phase(phase)
    │                     └ 'input'
    └ <flexget.task.Task object at 0x7f30364a29d0>
  File "/usr/lib/python3.8/site-packages/flexget/task.py", line 514, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
               │                 │       │      └ (<flexget.task.Task object at 0x7f30364a29d0>, {'host': '192.168.1.3', 'port': 9091, 'username': 'matthew', 'password': 'HSnk...
               │                 │       └ 'input'
               │                 └ <PluginInfo(name=from_transmission)>
               └ <flexget.task.Task object at 0x7f30364a29d0>
> File "/usr/lib/python3.8/site-packages/flexget/task.py", line 547, in __run_plugin
    result = method(*args, **kwargs)
             │       │       └ {}
             │       └ (<flexget.task.Task object at 0x7f30364a29d0>, {'host': '192.168.1.3', 'port': 9091, 'username': 'matthew', 'password': 'HSnk...
             └ <Event(name=plugin.from_transmission.input,func=on_task_input,priority=128)>
  File "/usr/lib/python3.8/site-packages/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ (<flexget.task.Task object at 0x7f30364a29d0>, {'host': '192.168.1.3', 'port': 9091, 'username': 'matthew', 'password': 'HSnk...
           │    └ <bound method PluginTransmissionInput.on_task_input of <flexget.plugins.clients.transmission.PluginTransmissionInput object a...
           └ <Event(name=plugin.from_transmission.input,func=on_task_input,priority=128)>
  File "/usr/lib/python3.8/site-packages/flexget/plugins/clients/transmission.py", line 186, in on_task_input
    self.client.http_handler.set_authentication(
    │    └ <transmission_rpc.client.Client object at 0x7f30366aeaf0>
    └ <flexget.plugins.clients.transmission.PluginTransmissionInput object at 0x7f3039506ca0>

AttributeError: 'Client' object has no attribute 'http_handler'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flexget/task.py", line 547, in __run_plugin
    result = method(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/flexget/plugins/clients/transmission.py", line 186, in on_task_input
    self.client.http_handler.set_authentication(
AttributeError: 'Client' object has no attribute 'http_handler'

**Comment by ksurl** [comment]
duplicate of [#2794](https://github.com/Flexget/Flexget/issues/2794)

**Comment by ProteinPig** [comment]
it's ok since i upgrade to 3.1.97
