### ISSUE TITLE
BUG: Unhandled error in plugin list_queue: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by seg7** [Flexget/Flexget#1135]
Lastest 2.0.10, config worked fine on 2.0.9

```
2016-05-04 12:00 CRITICAL task          movies_queue    BUG: Unhandled error in plugin list_queue: 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flexget/task.py", line 442, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flexget/plugins/filter/list_queue.py", line 37, in on_task_filter
    result = thelist.get(entry)
  File "/usr/local/lib/python2.7/site-packages/flexget/utils/database.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flexget/plugins/list/movie_list.py", line 187, in get
    match = self._find_entry(entry=entry, session=session)
  File "/usr/local/lib/python2.7/site-packages/flexget/utils/database.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flexget/plugins/list/movie_list.py", line 171, in _find_entry
    res = (self._db_list(session).movies.filter(func.lower(MovieListMovie.title) == name.lower())
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by liiight** [comment]
pushed a fix for that one already, should be out next release: https://github.com/Flexget/Flexget/commit/084731d07e0d9e800b5c8a96aba5b566fa42fe4e
