### ISSUE TITLE
All filters regarding PATH stop working pathdir pathbase after v3.15.27

### ISSUE THREAD

**Issue by Anian-igor** [Flexget/Flexget#4329]
### Expected behaviour:

Previously worked template {{location | pathdir }} or {{location | pathdir | pathbase }} stopped worked with error 
`Error during rendering: (AttributeError) 'str' object has no attribute 'parent'`

### Actual behaviour:

cannor parse location

### Steps to reproduce:
```
exec:
  - echo "location {{location}}"
  - echo "pathbase{{location|pathbase}}"
```
worked on version 3.15.26, not worked after 3.15.27

#### Config:
```dropbox_series_settings:
    filesystem:
      path:
        - "/tv/share/flexget/nextcloud/tvseries/"
      mask: '*.torrent'
      retrieve: files
    accept_all: yes
    exec:
      auto_escape: yes
      on_output:
        for_accepted: 
          - rm -f -- "{{ location }}"
          - echo "series_name {{series_name}}"
          - echo "location {{location}}"
          - echo "pathbase{{location|pathbase}}"
          - echo 'pathdir {{location | pathdir}}'
          - echo "pathbase{{location|pathdir|pathbase}}"
    set:
      label: "tv-{{location | pathdir | pathbase }}"
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
tv-DROPBOX-season-one phase_name: on_output operation: for_accepted cmd: rm -f -- "/tv/share/flexget/nextcloud/tvseries/Roadies s01.torrent"
2025-03-31 14:17:16.877902+00:002025-03-31 17:17:16 VERBOSE  exec          tv-DROPBOX-season-one Executing: rm -f -- "/tv/share/flexget/nextcloud/tvseries/Roadies s01.torrent"
2025-03-31 14:17:16.881561+00:002025-03-31 17:17:16 DEBUG    exec          tv-DROPBOX-season-one phase_name: on_output operation: for_accepted cmd: echo "series_name Roadies"
2025-03-31 14:17:16.881603+00:002025-03-31 17:17:16 VERBOSE  exec          tv-DROPBOX-season-one Executing: echo "series_name Roadies"
2025-03-31 14:17:16.882515+00:002025-03-31 17:17:16 INFO     exec          tv-DROPBOX-season-one Stdout: series_name Roadies
2025-03-31 14:17:16.884207+00:002025-03-31 17:17:16 DEBUG    exec          tv-DROPBOX-season-one phase_name: on_output operation: for_accepted cmd: echo "location /tv/share/flexget/nextcloud/tvseries/Roadies s01.torrent"
2025-03-31 14:17:16.884369+00:002025-03-31 17:17:16 VERBOSE  exec          tv-DROPBOX-season-one Executing: echo "location /tv/share/flexget/nextcloud/tvseries/Roadies s01.torrent"
2025-03-31 14:17:16.885569+00:002025-03-31 17:17:16 INFO     exec          tv-DROPBOX-season-one Stdout: location /tv/share/flexget/nextcloud/tvseries/Roadies s01.torrent
2025-03-31 14:17:16.887310+00:002025-03-31 17:17:16 DEBUG    utils.template tv-DROPBOX-season-one Error during rendering: (AttributeError) 'str' object has no attribute 'parent'
2025-03-31 14:17:16.887424+00:002025-03-31 17:17:16 ERROR    exec          tv-DROPBOX-season-one Could not set exec command for Roadies s01: (AttributeError) 'str' object has no attribute 'parent'
2025-03-31 14:17:16.889295+00:002025-03-31 17:17:16 DEBUG    utils.template tv-DROPBOX-season-one Error during rendering: (AttributeError) 'str' object has no attribute 'parent'
2025-03-31 14:17:16.889407+00:002025-03-31 17:17:16 ERROR    exec          tv-DROPBOX-season-one Could not set exec command for Roadies s01: (AttributeError) 'str' object has no attribute 'parent'
```
</details>

### Additional information:

- FlexGet version: 3.15.30
- Python version:
- Installation method:
- Using daemon (yes/no):
- OS and version:
- Link to crash log:

**Comment by Anian-igor** [comment]
Hello @vivodi 
You did a change https://github.com/Flexget/Flexget/commit/8b9d7ef966189133e91adb93f1bfb0d0b9aa1078
This change broke a path filters. Could you please review?

**Comment by vivodi** [comment]
**Thank you for reporting this issue!**  
I’m sorry for the bug introduced by the recent pull request. I’ve been able to reproduce the issue and I’m currently investigating the cause. I’ll work on fixing it as soon as possible and will keep you updated.

Thanks again for your valuable feedback, and I apologize for the inconvenience!
