### ISSUE TITLE
Flexget crashes after upgrading to 2.2.3

### ISSUE THREAD

**Issue by klein1jo** [Flexget/Flexget#1309]
#### Log:
```
CRITICAL plugin                        Exception while loading plugin flexget.plugins.metainfo.tmdb_lookup
Traceback (most recent call last):
  File "/opt/rh/python27/root/usr/lib64/python2.7/site-packages/flexget/plugin.py", line 395, in _load_plugins_from_dirs
    __import__(module_name)
  File "/opt/rh/python27/root/usr/lib64/python2.7/site-packages/flexget/plugins/metainfo/tmdb_lookup.py", line 9, in <module>
    from flexget.utils import imdb
  File "/opt/rh/python27/root/usr/lib64/python2.7/site-packages/flexget/utils/imdb.py", line 10, in <module>
    from bs4.element import Tag
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
```

### Additional information:
- Flexget Version: 2.2.3
- Python Version: 2.7
- Installation method: pip
- OS and version: CentOS 6

FlexGet crashes under all conditions (flexget check, flexget execute, etc...).  Python 2.7 is installed via CentOS Software Collections.  FlexGet is executed as follows:

/usr/bin/scl enable python27 'flexget execute'

In an attempt to remedy I tried the following:

- Removed Python 2.7
- Manually deleted /opt/rh/python27 to remove any remaining cruft
- Performed a clean install of Python 2.7
- Upgraded Python packages via pip
- Performed a clean install of FlexGet via pip
- Purged FlexGet directory of everything except config.yml
