### ISSUE TITLE
flexget fails to build with python-3.13

### ISSUE THREAD

**Issue by hboetes** [Flexget/Flexget#4026]
Whilst building flexget I ran into the following error:

```
      gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -O3 -fPIC -I/home/han/.virtualenv/flexget/include -I/usr/include/python3.13 -c src/greenlet/greenlet.cpp -o build/temp.linux-x86_64-cpython-313/src/greenlet/greenlet.o
      In file included from src/greenlet/greenlet_greenlet.hpp:26,
                       from src/greenlet/greenlet_internal.hpp:20,
                       from src/greenlet/greenlet.cpp:19:
      /usr/include/python3.13/internal/pycore_frame.h:8:4: error: #error "this header requires Py_BUILD_CORE define"
          8 | #  error "this header requires Py_BUILD_CORE define"
            |    ^~~~~
```
And then a lot more of the same. Whilst googling I ran into this report, which describes exactly the same problem:

https://src.fedoraproject.org/rpms/python-greenlet/c/d426d412697fad13bd735496ac1a934e29ad2a72?branch=rawhide

So please someone examine building flexget with python-3.13 and try to reproduce and then fix this problem.

**Comment by hboetes** [comment]
project is dead
