### ISSUE TITLE
failing after upgrade to 2.0.23

### ISSUE THREAD

**Issue by naseemr** [Flexget/Flexget#1188]
Getting the following error:

flexget execute
```
2016-05-16 11:58 CRITICAL plugin                        Plugin `flexget.plugins.urlrewrite_koreus` failed to import dependencies
2016-05-16 11:58 ERROR    plugin                        cannot import name urlopener
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 387, in _load_plugins_from_dirs
    __import__(module_name)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/urlrewrite_koreus.py", line 9, in <module>
    from flexget.utils.tools import urlopener
ImportError: cannot import name urlopener
2016-05-16 11:58 CRITICAL plugin                        Plugin `flexget.plugins.urlrewrite_newzleech` failed to import dependencies
2016-05-16 11:58 ERROR    plugin                        cannot import name urlopener
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 387, in _load_plugins_from_dirs
    __import__(module_name)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/urlrewrite_newzleech.py", line 11, in <module>
    from flexget.utils.tools import urlopener
ImportError: cannot import name urlopener
2016-05-16 11:58 CRITICAL plugin                        Plugin `flexget.plugins.urlrewrite_google_cse` failed to import dependencies
2016-05-16 11:58 ERROR    plugin                        cannot import name urlopener
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 387, in _load_plugins_from_dirs
    __import__(module_name)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/urlrewrite_google_cse.py", line 12, in <module>
    from flexget.utils.tools import urlopener
ImportError: cannot import name urlopener
2016-05-16 11:58 CRITICAL plugin                        Plugin `flexget.plugins.urlrewrite_bakabt` failed to import dependencies
2016-05-16 11:58 ERROR    plugin                        cannot import name urlopener
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 387, in _load_plugins_from_dirs
    __import__(module_name)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/urlrewrite_bakabt.py", line 8, in <module>
    from flexget.utils.tools import urlopener
ImportError: cannot import name urlopener
2016-05-16 11:58 CRITICAL plugin                        Plugin `flexget.plugins.urlrewrite_newtorrents` failed to import dependencies
2016-05-16 11:58 ERROR    plugin                        cannot import name urlopener
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 387, in _load_plugins_from_dirs
    __import__(module_name)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/urlrewrite_newtorrents.py", line 13, in <module>
    from flexget.utils.tools import urlopener
ImportError: cannot import name urlopener
2016-05-16 11:58 CRITICAL plugin                        Plugin `flexget.plugins.urlrewrite_frenchtorrentdb` failed to import dependencies
2016-05-16 11:58 ERROR    plugin                        cannot import name urlopener
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 387, in _load_plugins_from_dirs
    __import__(module_name)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/urlrewrite_frenchtorrentdb.py", line 8, in <module>
    from flexget.utils.tools import urlopener
ImportError: cannot import name urlopener
2016-05-16 11:58 CRITICAL plugin                        Plugin `flexget.plugins.urlrewrite_deadfrog` failed to import dependencies
2016-05-16 11:58 ERROR    plugin                        cannot import name urlopener
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 387, in _load_plugins_from_dirs
    __import__(module_name)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/urlrewrite_deadfrog.py", line 9, in <module>
    from flexget.utils.tools import urlopener
ImportError: cannot import name urlopener
2016-05-16 11:58 CRITICAL plugin                        Exception while loading plugin flexget.plugins.urlrewrite_torrent411
2016-05-16 11:58 ERROR    plugin                        Table 't411_accounts' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 387, in _load_plugins_from_dirs
    __import__(module_name)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/urlrewrite_torrent411.py", line 214, in <module>
    class torrent411Account(Base):
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/declarative/api.py", line 55, in __init__
    _as_declarative(cls, classname, cls.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/declarative/base.py", line 88, in _as_declarative
    _MapperConfig.setup_mapping(cls, classname, dict_)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/declarative/base.py", line 103, in setup_mapping
    cfg_cls(cls_, classname, dict_)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/declarative/base.py", line 131, in __init__
    self._setup_table()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/declarative/base.py", line 394, in _setup_table
    **table_kw)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/schema.py", line 398, in __new__
    "existing Table object." % key)
InvalidRequestError: Table 't411_accounts' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
Traceback (most recent call last):
  File "/usr/local/bin/flexget", line 9, in <module>
    load_entry_point('FlexGet==1.2.455', 'console_scripts', 'flexget')()
  File "/usr/local/lib/python2.7/dist-packages/flexget/__init__.py", line 42, in main
    manager.start()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 309, in start
    self.initialize()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 181, in initialize
    plugin.load_plugins(extra_dirs=[os.path.join(self.config_base, 'plugins')])
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 431, in load_plugins
    _load_plugins_from_dirs(extra_dirs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 387, in _load_plugins_from_dirs
    __import__(module_name)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/urlrewrite_torrent411.py", line 214, in <module>
    class torrent411Account(Base):
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/declarative/api.py", line 55, in __init__
    _as_declarative(cls, classname, cls.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/declarative/base.py", line 88, in _as_declarative
    _MapperConfig.setup_mapping(cls, classname, dict_)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/declarative/base.py", line 103, in setup_mapping
    cfg_cls(cls_, classname, dict_)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/declarative/base.py", line 131, in __init__
    self._setup_table()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/declarative/base.py", line 394, in _setup_table
    **table_kw)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/schema.py", line 398, in __new__
    "existing Table object." % key)
sqlalchemy.exc.InvalidRequestError: Table 't411_accounts' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
```
naseemr@naseemr-ubuntu:~/.flexget$   flexget -V
2.0.23
You are on the latest release.
naseemr@naseemr-ubuntu:~/.flexget$

**Comment by cvium** [comment]
Something is broken. Try a complete reinstall of Flexget.

**Comment by crawln45** [comment]
think this should force upgrade everything.
```
pip install --upgrade --force-reinstall flexget
```

**Comment by naseemr** [comment]
Thank you, I had to reinstall pip and flexget to get it to work again.

**Comment by crawln45** [comment]
Closing as resolved by user.
