### ISSUE TITLE
Conflicting dependency with cloudscraper

### ISSUE THREAD

**Issue by BrutuZ** [Flexget/Flexget#2666]
Updating `cloudscraper` is part of my launch script for FlexGet, today it started giving me errors since they upgraded their requirements to `pyparsing >= 2.4.7` (https://github.com/VeNoMouS/cloudscraper/commit/62e15d88f20d251c1cf8be9c096d488cbc04b44e) while FlexGet is tied to `pyparsing == 2.2.0` and AFAIK they need to be on the same virtual environment for the `cfscraper` plugin to work.
#### Log:
<details>
 <summary>(click to expand)</summary>

```
$ pip install cloudscraper
Requirement already satisfied: cloudscraper in github\flexget\lib\site-packages (1.2.36)
Requirement already satisfied: requests-toolbelt>=0.9.1 in github\flexget\lib\site-packages (from cloudscraper) (0.9.1)
Collecting pyparsing>=2.4.7
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Requirement already satisfied: requests>=2.9.2 in github\flexget\lib\site-packages (from cloudscraper) (2.21.0)
Requirement already satisfied: certifi>=2017.4.17 in github\flexget\lib\site-packages (from requests>=2.9.2->cloudscraper) (2017.4.17)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in github\flexget\lib\site-packages (from requests>=2.9.2->cloudscraper) (1.24.2)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in github\flexget\lib\site-packages (from requests>=2.9.2->cloudscraper) (3.0.3)
Requirement already satisfied: idna<2.9,>=2.5 in github\flexget\lib\site-packages (from requests>=2.9.2->cloudscraper) (2.8)
ERROR: flexget 3.1.51 has requirement pyparsing==2.2.0, but you'll have pyparsing 2.4.7 which is incompatible.
Installing collected packages: pyparsing
  Attempting uninstall: pyparsing
    Found existing installation: pyparsing 2.2.0
    Uninstalling pyparsing-2.2.0:
      Successfully uninstalled pyparsing-2.2.0
Successfully installed pyparsing-2.4.7
```
</details>

### Additional information:

- FlexGet version: 3.1.51
- Python version: 3.7
- Installation method: git
- Using daemon (yes/no): yes
- OS and version: Win10

**Comment by BrutuZ** [comment]
Seems CF updated their challenge and as such CloudScraper **needs** to be updated in order to avoid tasks being aborted.
I manually updated a single character in `requirements.txt` and it didn't seem to break anything (haven't run tests yet, this is not a PR anyways) while allowing for a CloudScraper update and passing the CF challenge.
```diff
diff --git a/requirements.txt b/requirements.txt
index bd674aa44..15cfa926b 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -35,7 +35,7 @@ plumbum==1.6.3            # via rpyc
 portend==2.6              # via cherrypy
 progressbar==2.5          # via -r requirements.in
 pynzb==0.1.0              # via -r requirements.in
-pyparsing==2.2.0          # via -r requirements.in
+pyparsing>=2.2.0          # via -r requirements.in
 pyrss2gen==1.1            # via -r requirements.in
 python-dateutil==2.6.1    # via -r requirements.in, aniso8601, guessit
 pytz==2017.2              # via apscheduler, flask-restful, flask-restplus, tempora, tzlocal
```
<details>
<summary>LOG</summary>

```
2020-05-29 17:40:12 DEBUG    download      download-series-rss Downloading url 'https://itorrents.org/torrent/8411E1CBE4F4C266E45ECA501AF803850F423F78.torrent?title=Marvels-Agents-of-S-H-I-E-L-D-S07E01-720p-AMZN-WEB-DL-DDP5-1-H-264-T6D[eztv-io]'
2020-05-29 17:40:12 DEBUG    utils.requests download-series-rss GETing URL https://itorrents.org/torrent/8411E1CBE4F4C266E45ECA501AF803850F423F78.torrent?title=Marvels-Agents-of-S-H-I-E-L-D-S07E01-720p-AMZN-WEB-DL-DDP5-1-H-264-T6D[eztv-io] with args () and kwargs {'auth': None, 'headers': OrderedDict([('User-Agent', 'FlexGet/3.1.59 (www.flexget.com)'), ('Accept', 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'), ('Accept-Language', 'en-US,en;q=0.5'), ('Accept-Encoding', 'gzip, deflate'), ('Connection', 'close'), ('Upgrade-Insecure-Requests', '1'), ('If-Modified-Since', 'Fri, 29 May 2020 20:19:02 GMT'), ('If-None-Match', '"5ed16e36-122c2"')]), 'allow_redirects': True, 'timeout': 30}
2020-05-29 17:40:16 CRITICAL task          download-series-rss BUG: Unhandled error in plugin qbittorrent: Unable to parse Cloudflare anti-bots page: Error trying to solve Cloudflare IUAM Javascript, they may have changed their technique.
AttributeError: 'NoneType' object has no attribute 'groupdict'


During handling of the above exception, another exception occurred:


cloudscraper.exceptions.CloudflareSolveError: There was an issue extracting the Cloudflare challenge.


During handling of the above exception, another exception occurred:


cloudscraper.exceptions.CloudflareSolveError: Error trying to solve Cloudflare IUAM Javascript, they may have changed their technique.


During handling of the above exception, another exception occurred:


cloudscraper.exceptions.CloudflareIUAMError: Unable to parse Cloudflare anti-bots page: Error trying to solve Cloudflare IUAM Javascript, they may have changed their technique.
Traceback (most recent call last):
AttributeError: 'NoneType' object has no attribute 'groupdict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
cloudscraper.exceptions.CloudflareSolveError: There was an issue extracting the Cloudflare challenge.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
cloudscraper.exceptions.CloudflareSolveError: Error trying to solve Cloudflare IUAM Javascript, they may have changed their technique.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
cloudscraper.exceptions.CloudflareIUAMError: Unable to parse Cloudflare anti-bots page: Error trying to solve Cloudflare IUAM Javascript, they may have changed their technique.
```

</details>

**Comment by evoblicec** [comment]
Did you get your task working with `cloudscraper  1.2.40`? Still don't work after the upgrade on my side.

**Comment by BrutuZ** [comment]
It would appear so. Had no more errors after locally updating the requirements files and updating CloudScraper.

Tried a couple random links on a test config just now to confirm Flexget just didn't happen to switch to an unprotected source before answering this but stumbled on an unusual situation where CF doesn't seem to be challenging requests.
The task went through before I even added the `cfscraper: yes` plugin, even raw `curl` request from terminal returned the content instead of challenge page. Will look for other URLs for further testing

**Comment by ccharlot** [comment]
With the latest version of clouscraper, my tasks fail to complete, I get this message: 
2020-05-31 17:44:09 CRITICAL plugin        FILMS           Cannot set verify_mode to CERT_NONE when check_hostname is enabled.
2020-05-31 17:44:09 WARNING  task          FILMS           Aborting task (plugin: rss)

Any Idea ?
part off config.yml is :
    rss: https://www2.yggtorrent.se/rss?action=generate&type=subcat&id=2183&passkey=xxx
    cfscraper: yes
